### ISSUE TITLE
retroshare.org domain missing 

### ISSUE THREAD

**Issue by cavebeat** [RetroShare/retroshare.github.io#23]
At the moment retroshare.org points to retroshare.sourceforge.net -> which forwards to https://retroshare.github.io/

In the Header:
Broken: 
Wiki -> http://retroshare.sourceforge.net/wiki/index.php/ -> https://github.com/RetroShare/RetroShare/wiki

In the Footer:

Works:
Project Site -> https://sourceforge.net/projects/retroshare/
Screenshots -> https://retroshare.github.io/screenshots.html
GitHub project page -> https://github.com/RetroShare
DevBlog -> https://retroshareteam.wordpress.com/
Web forums -> http://retroshare.sourceforge.net/forum

Broken Links: 
Documentation: http://retroshare.sourceforge.net/wiki/index.php/Documentation
FAQ: http://retroshare.sourceforge.net/wiki/index.php/Frequently_Asked_Questions
Wiki: http://retroshare.sourceforge.net/wiki/index.php/
Developer mailing list: http://sourceforge.net/p/retroshare/mailman/

Twitter is available three times

**Comment by felisucoibi** [comment]
this can be closed too
